/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gamemode = IDL.Variant({
  'Axe' : IDL.Null,
  'SMP' : IDL.Null,
  'UHC' : IDL.Null,
  'Sword' : IDL.Null,
  'Mace' : IDL.Null,
  'Crystal' : IDL.Null,
  'Spearmace' : IDL.Null,
  'DiamondSMP' : IDL.Null,
});
export const Tier = IDL.Variant({
  'HT1' : IDL.Null,
  'HT2' : IDL.Null,
  'HT3' : IDL.Null,
  'HT4' : IDL.Null,
  'HT5' : IDL.Null,
  'LT1' : IDL.Null,
  'LT2' : IDL.Null,
  'LT3' : IDL.Null,
  'LT4' : IDL.Null,
  'LT5' : IDL.Null,
});
export const RankedPerson = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'tier' : Tier,
});

export const idlService = IDL.Service({
  'addPersonToTier' : IDL.Func([Gamemode, Tier, IDL.Text, IDL.Text], [], []),
  'getAllTiers' : IDL.Func(
      [Gamemode],
      [IDL.Vec(IDL.Tuple(Tier, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([Gamemode], [IDL.Vec(RankedPerson)], ['query']),
  'removePersonFromTier' : IDL.Func(
      [Gamemode, Tier, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gamemode = IDL.Variant({
    'Axe' : IDL.Null,
    'SMP' : IDL.Null,
    'UHC' : IDL.Null,
    'Sword' : IDL.Null,
    'Mace' : IDL.Null,
    'Crystal' : IDL.Null,
    'Spearmace' : IDL.Null,
    'DiamondSMP' : IDL.Null,
  });
  const Tier = IDL.Variant({
    'HT1' : IDL.Null,
    'HT2' : IDL.Null,
    'HT3' : IDL.Null,
    'HT4' : IDL.Null,
    'HT5' : IDL.Null,
    'LT1' : IDL.Null,
    'LT2' : IDL.Null,
    'LT3' : IDL.Null,
    'LT4' : IDL.Null,
    'LT5' : IDL.Null,
  });
  const RankedPerson = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'tier' : Tier,
  });
  
  return IDL.Service({
    'addPersonToTier' : IDL.Func([Gamemode, Tier, IDL.Text, IDL.Text], [], []),
    'getAllTiers' : IDL.Func(
        [Gamemode],
        [IDL.Vec(IDL.Tuple(Tier, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([Gamemode], [IDL.Vec(RankedPerson)], ['query']),
    'removePersonFromTier' : IDL.Func(
        [Gamemode, Tier, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };