/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gamemode = { 'Axe' : null } |
  { 'SMP' : null } |
  { 'UHC' : null } |
  { 'Sword' : null } |
  { 'Mace' : null } |
  { 'Crystal' : null } |
  { 'Spearmace' : null } |
  { 'DiamondSMP' : null };
export interface RankedPerson {
  'name' : string,
  'rank' : bigint,
  'tier' : Tier,
}
export type Tier = { 'HT1' : null } |
  { 'HT2' : null } |
  { 'HT3' : null } |
  { 'HT4' : null } |
  { 'HT5' : null } |
  { 'LT1' : null } |
  { 'LT2' : null } |
  { 'LT3' : null } |
  { 'LT4' : null } |
  { 'LT5' : null };
export interface _SERVICE {
  'addPersonToTier' : ActorMethod<[Gamemode, Tier, string, string], undefined>,
  'getAllTiers' : ActorMethod<[Gamemode], Array<[Tier, Array<string>]>>,
  'getLeaderboard' : ActorMethod<[Gamemode], Array<RankedPerson>>,
  'removePersonFromTier' : ActorMethod<
    [Gamemode, Tier, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];