/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RankedPerson {
    name: string;
    rank: bigint;
    tier: Tier;
}
export enum Gamemode {
    Axe = "Axe",
    SMP = "SMP",
    UHC = "UHC",
    Sword = "Sword",
    Mace = "Mace",
    Crystal = "Crystal",
    Spearmace = "Spearmace",
    DiamondSMP = "DiamondSMP"
}
export enum Tier {
    HT1 = "HT1",
    HT2 = "HT2",
    HT3 = "HT3",
    HT4 = "HT4",
    HT5 = "HT5",
    LT1 = "LT1",
    LT2 = "LT2",
    LT3 = "LT3",
    LT4 = "LT4",
    LT5 = "LT5"
}
export interface backendInterface {
    addPersonToTier(gamemode: Gamemode, tier: Tier, person: string, accessCode: string): Promise<void>;
    getAllTiers(gamemode: Gamemode): Promise<Array<[Tier, Array<string>]>>;
    getLeaderboard(gamemode: Gamemode): Promise<Array<RankedPerson>>;
    removePersonFromTier(gamemode: Gamemode, tier: Tier, person: string, accessCode: string): Promise<void>;
}
import type { Gamemode as _Gamemode, RankedPerson as _RankedPerson, Tier as _Tier } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPersonToTier(arg0: Gamemode, arg1: Tier, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPersonToTier(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tier_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPersonToTier(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tier_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async getAllTiers(arg0: Gamemode): Promise<Array<[Tier, Array<string>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTiers(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTiers(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: Gamemode): Promise<Array<RankedPerson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async removePersonFromTier(arg0: Gamemode, arg1: Tier, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePersonFromTier(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tier_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePersonFromTier(to_candid_Gamemode_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tier_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
}
function from_candid_RankedPerson_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankedPerson): RankedPerson {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Tier_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tier): Tier {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    rank: bigint;
    tier: _Tier;
}): {
    name: string;
    rank: bigint;
    tier: Tier;
} {
    return {
        name: value.name,
        rank: value.rank,
        tier: from_candid_Tier_n7(_uploadFile, _downloadFile, value.tier)
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tier, Array<string>]): [Tier, Array<string>] {
    return [
        from_candid_Tier_n7(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HT1: null;
} | {
    HT2: null;
} | {
    HT3: null;
} | {
    HT4: null;
} | {
    HT5: null;
} | {
    LT1: null;
} | {
    LT2: null;
} | {
    LT3: null;
} | {
    LT4: null;
} | {
    LT5: null;
}): Tier {
    return "HT1" in value ? Tier.HT1 : "HT2" in value ? Tier.HT2 : "HT3" in value ? Tier.HT3 : "HT4" in value ? Tier.HT4 : "HT5" in value ? Tier.HT5 : "LT1" in value ? Tier.LT1 : "LT2" in value ? Tier.LT2 : "LT3" in value ? Tier.LT3 : "LT4" in value ? Tier.LT4 : "LT5" in value ? Tier.LT5 : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Tier, Array<string>]>): Array<[Tier, Array<string>]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RankedPerson>): Array<RankedPerson> {
    return value.map((x)=>from_candid_RankedPerson_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Gamemode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gamemode): _Gamemode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Tier_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tier): _Tier {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gamemode): {
    Axe: null;
} | {
    SMP: null;
} | {
    UHC: null;
} | {
    Sword: null;
} | {
    Mace: null;
} | {
    Crystal: null;
} | {
    Spearmace: null;
} | {
    DiamondSMP: null;
} {
    return value == Gamemode.Axe ? {
        Axe: null
    } : value == Gamemode.SMP ? {
        SMP: null
    } : value == Gamemode.UHC ? {
        UHC: null
    } : value == Gamemode.Sword ? {
        Sword: null
    } : value == Gamemode.Mace ? {
        Mace: null
    } : value == Gamemode.Crystal ? {
        Crystal: null
    } : value == Gamemode.Spearmace ? {
        Spearmace: null
    } : value == Gamemode.DiamondSMP ? {
        DiamondSMP: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tier): {
    HT1: null;
} | {
    HT2: null;
} | {
    HT3: null;
} | {
    HT4: null;
} | {
    HT5: null;
} | {
    LT1: null;
} | {
    LT2: null;
} | {
    LT3: null;
} | {
    LT4: null;
} | {
    LT5: null;
} {
    return value == Tier.HT1 ? {
        HT1: null
    } : value == Tier.HT2 ? {
        HT2: null
    } : value == Tier.HT3 ? {
        HT3: null
    } : value == Tier.HT4 ? {
        HT4: null
    } : value == Tier.HT5 ? {
        HT5: null
    } : value == Tier.LT1 ? {
        LT1: null
    } : value == Tier.LT2 ? {
        LT2: null
    } : value == Tier.LT3 ? {
        LT3: null
    } : value == Tier.LT4 ? {
        LT4: null
    } : value == Tier.LT5 ? {
        LT5: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
